<?php

namespace AppBundle\Repository;

/**
 * FrontPageItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrontPageItemRepository extends \Doctrine\ORM\EntityRepository
{
}
