user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
generalApp:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults: { _controller: AppBundle:User:login }