# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    #comentar ?
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: plaintext

    # comentar users
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

        login:
                    pattern:  ^/login$
                    stateless: true
                    knpu_guard:
                        authenticators:
                            - username_password_guard_authenticator

                api:
                    pattern: ^/api
                    stateless: true
                    knpu_guard:
                        authenticators:
                            - jwt_guard_authenticator


